project_id = "bilgoxmvnvhiqzidllvj"

[functions.create-order]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.save-order]
verify_jwt = false

[functions.send-contact-inquiry]
verify_jwt = false