project_id = "bilgoxmvnvhiqzidllvj"

[functions.create-order]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.save-order]
verify_jwt = false

[functions.send-contact-inquiry]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-status-update]
verify_jwt = false

[functions.meta-product-feed]
verify_jwt = false

[functions.seed-products]
verify_jwt = false